image: 'golang:latest'

stages:
#  - test
  - release-linux
#  - build-docker
#  - windows

#test:linux:
#  stage: test
#  script:     
#    - cd ./src
#    - go get gopkg.in/yaml.v2
#    - go test -v
      
release:linux:
  stage: release-linux
#  only: 
#    - tags    
  script:     
    - cd ./src
    - go get gopkg.in/yaml.v2
    - go test -v
    - go build -v
    - mv src ../ezrep
    - cd ..
    - curl -L -o upx.tar.xz  https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz
    - tar -xf upx.tar.xz upx-3.94-amd64_linux/upx
    - cp upx-3.94-amd64_linux/upx upx
    - upx ezrep
    - tar -cvzf ezrep-$CI_COMMIT_TAG.tar.gz ezrep    
  artifacts:
    name: 'ezrep-$CI_COMMIT_TAG'
    paths:
      - ezrep-*

# build:docker:
#   stage: build-docker
#   image: 'docker:stable'
#   services:
#    - 'docker:dind'
#   script:
#     - docker build -t ezrep .
#     - push

# windows_job:
#   stage: windows
#   image: 'golang:nanoserver'
#   script: 
#     - cd ./src
#     - go test -v
#     - go build
#     - move src.exe ../ezrep.exe
#   artifacts:
#     paths:
#      - ezrep.exe
      