image: 'golang:1.10'

stages:
  - test
  - build
  - release

test:branch:  
  stage: test   
  except:
    refs:
      - master
      - develop
  script:     
    - ./build.sh 
      download-go
      test-go    
  
build:develop:
  stage: build
  only: 
    refs:
      - develop 
  script:    
    - ./build.sh 
      download-semrel 
      download-go 
      build-go 
      test-go
      package-beta          
  artifacts:
    name: ezrep-prerelease
    paths:
      - ezrep-* 

build:master:
  stage: build
  only:
    refs:
      - master
  except:
    - tags
  script:
    - ./build.sh 
      download-semrel
      download-go
      build-go
      package-release
      tag-release    
  artifacts:
    name: ezrep-release
    paths:
      - ezrep-*      

publish:master:
  stage: release
  only:
    - tags
  dependencies:
     - build:master  
  script:
    - ./build.sh 
      download-semrel
      publish-release
