stages:
  - test
  - build
  - package
  - release

test:executable:  
  stage: test   
  image: 'golang:1.10' 
  except:
    refs:
      - master
      - develop
  script:     
    - cd ./src
    - go get gopkg.in/yaml.v2
    - go test -v

download:release:
  stage: build
  only:
    refs:
      - master
      - develop
  script:
    - curl -L -o release https://gitlab.com/juhani/go-semrel-gitlab/uploads/222a87259f6162c1a59c8586226f61cf/release
    - chmod +x release
    - ./release -v    
  artifacts:
    expire_in: '20 mins'
    paths:
      - release

build:executable:
  stage: build 
  image: 'golang:1.10'
  only: 
    refs:
      - master
      - develop   
  script:     
    - cd ./src
    - go get gopkg.in/yaml.v2
    - go test -v
    - go build -v
    - mv src ../ezrep
    - chmod +x ../ezrep
  artifacts:
    expire_in: '20 mins'
    paths:
      - ezrep
  
package:develop:
  stage: package
  only: 
    refs:
      - develop 
  dependencies:
    - build:executable
    - download:release
  script:
    - export SEMVER=$(./release next-version -p)
    - echo $SEMVER    
    - tar -cvzf ezrep-$SEMVER-pre.tar.gz ezrep    
  artifacts:
    name: ezrep-prerelease
    paths:
      - ezrep-* 

package:master:
  stage: package
  only:
    refs:
      - master
  except:
    - tags
  dependencies:
    - build:executable
    - download:release
  script:
    - export SEMVER=$(./release next-version -p)
    - echo $SEMVER    
    - tar -cvzf ezrep-$SEMVER.tar.gz ezrep        
    - ./release changelog
    - ./release commit-and-tag CHANGELOG.md
  artifacts:
    name: ezrep-release
    paths:
      - ezrep-* 

publish:master:
  stage: release
  only:
    - tags
  dependencies:
    - package:master
  script:
    - export SEMVER=$(./release next-version -p)
    - echo $SEMVER    
    - ./release add-download -f ezrep-$SEMVER.tar.gz -d "Linux executable"



