image: 'golang:1.10'

stages:
  - test
  - build
#  - release

test:branch:  
  stage: test   
  except:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
      - $CI_COMMIT_REF_NAME == "develop"
#    refs:
#      - master
#      - develop
  script:     
    - ./build.sh 
      download-go
      test-go    
  
build:develop:
  stage: build
  only: 
    variables:
      - $CI_COMMIT_REF_NAME == "develop"
#    refs:
#      - develop 
  script:    
    - ./build.sh 
      download-semrel 
      download-go 
      build-go 
      test-go
      package-beta          
  artifacts:
    name: ezrep-prerelease
    paths:
      - ezrep-* 

build:master:
  stage: build
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
#    refs:
#      - master
  except:
    - tags
  script:
    - ./build.sh 
      download-semrel
      download-go
      build-go
      package-release
      tag-release
      publish-release
  artifacts:
    name: ezrep-release
    paths:
      - ezrep-*      

#publish:master:
#  stage: release
#  only:
#    - tags
#  dependencies:
#     - build:master  
#  script:
#    - ./build.sh 
#      download-semrel
#      publish-release
